rabbitmq:
  image: rabbitmq:management
  restart: always
  ports:
    - '5672:5672'
    - '15672:15672'
  volumes:
    - ./conf/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    - ./conf/definitions.json:/etc/rabbitmq/definitions.json:ro
